# Generated by Django 3.2.4 on 2021-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='image_mise_en_avant',
            field=models.ImageField(default='ibsnoimage.png', upload_to='besoin'),
        ),
    ]
