# Generated by Django 3.2.4 on 2021-10-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donateur', '0001_initial'),
        ('core', '0003_auto_20211024_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='donateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donateur.donateur'),
        ),
    ]
