# Generated by Django 3.2.4 on 2021-10-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant', '0002_alter_gerant_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gerant',
            name='nom',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='gerant',
            name='prenom',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
