# Generated by Django 3.2.4 on 2021-10-23 23:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisation', models.CharField(max_length=40)),
                ('logo_partenaire', models.ImageField(default='noimage.png', upload_to='logo')),
                ('description', models.TextField(default='Aucune Description')),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('tel1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('tel2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
